// <auto-generated />
namespace YoloBlogger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v2Added_Date_Fi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2Added_Date_Fi));
        
        string IMigrationMetadata.Id
        {
            get { return "202004081513568_v2-Added_Date_Fi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
